version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
  build:
    commands:
      - echo "Building Go binary..."
      - cd src/go
      - go build -o my-app main.go
      - cd ..
  post_build:
    commands:
      - zip -r src/sample.zip src/go/my-app
      - ls -l src
      - echo "Build finished."

artifacts:
  type: zip
  files:
    - sample.zip
    - appspec.yml
    - script
  base-directory: src
  name: sample.zip