version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
  build:
    commands:
      - echo "Building Go binary..."
      - cd src
      - go build -o my-app main.go
  post_build:
    commands:
      - zip -r sample.zip appspec.yml my-app script/
      - cd ..
      - echo "Build finished."

artifacts:
  files:
      - sample.zip
