version: 0.0
os: linux
files:
  - source: src/my-app
    destination: /opt/my-app/
hooks:
  BeforeInstall:
    - location: src/script/clean.sh  # ★ src/ を追加！
      timeout: 300
      runas: root
  ApplicationStart:
    - location: src/script/start.sh  # ★ src/ を追加！
      timeout: 300
      runas: root

# Linux上でGoバイナリを実行できるように権限(755)を与える設定
permissions:
  - object: /opt/my-app/my-app
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file